services:
  - type: docker
    name: app
    buildCommand: docker build -t my-app .
    startCommand: docker run --name my-app -p 3001:3001 -v $(pwd):/home/node/app my-app
    env:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - port: 3001:3001
        protocol: tcp
