version: '3'
services:
  app:
    build: .
    container_name: mindi-App2
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: '4.0'
    restart: always
    tty: true
    entrypoint: ./docker/entrypoint.sh
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
